### PR TITLE
sw-precache article

### PR DESCRIPTION
**Pull request by jeffposnick**
@PaulKinlan, the content has already gone through an out-of-band review.

### CODE REVIEW

**Comment by jeffposnick** [comment]
@addyosmani has some additional out-of-band feedback, which I'll integrate into this PR, so this isn't ready to merge quite yet.

**Comment by PaulKinlan** [comment]
Ok, it has a build error too so j need to fix that.

**Comment by jeffposnick** [comment]
I think that takes care of the feedback from @addyosmani.

Re: the Travis CI failure, it's related to the `openssl` decryption step. @PaulKinlan, it [looks like](https://github.com/html5rocks/updates.html5rocks.com.new/commits/development/.travis.yml) you added in the Travis integration recently. I'm not familiar with what it's doing, but looking at a successful build from 5 days ago, I see [`Setting environment variables from repository settings`](https://travis-ci.org/html5rocks/updates.html5rocks.com.new/builds/51240809#L90) message logged, but I don't see that in the build that was triggered by my PR.

Where those environment variables are supposed to get picked up from?

**Comment by PaulKinlan** [comment]
These are secure env variables, unless they changed. Travis didn't deploy
to app engine due to an issue with app engine not supporting our
configuration.... I'll sort that out.

P

**Comment by PaulKinlan** [comment]
Ok, cool.  So I had it set to deploy pull requests which is why I believe this failed.  The enviroment variables aren't the same.  I have changed the travis config to only do it on commit.

**Pull request merged**
