### PR TITLE
Adds feeds redirects to DevSite

### PR DESCRIPTION
**Pull request by petele**
@PaulKinlan - will want to merge when we're both online Friday.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
I also have a full redirecror too... Let's sync.

**Comment by petele** [comment]
OK - grab me in the morning tomorrow. 

I know you were working on a direct for the whole site, so this was meant as a stop gap to redirect the RSS/ATOM feeds until we make the full transition.

**Comment by PaulKinlan** [comment]
SG. Happy to exclude feeds from my bit... Side note we need RSS feed on wf.

**Comment by petele** [comment]
Removing this for the time being.

**Pull request closed without merging**
